# Site settings
title: DC Capital Striders
email: contact@dccapitalstriders.com
description: > # this means to ignore newlines until "baseurl:"
  DC Capital Striders is a community of runners in Washington, D.C., Northern Virginia, and Maryland. Membership is free and open to anyone. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dccapitalstriders.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
