# Site settings
title: DC Capital Striders
email: contact@dccapitalstriders.com
description: > # this means to ignore newlines until "baseurl:"
  DC Capital Striders is a community of runners in Washington, D.C., Northern Virginia, and Maryland. Membership is free and open to anyone. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dccapitalstriders.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title/

# Prose
prose:
  metadata:
    _posts/events:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "category"
        field:
          element: "hidden"
          label: "events"
    _posts/races:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "category"
        field:
          element: "hidden"
          label: "races"
  ignore:
    - _config.yml
    - /.sass-cache
    - /_layouts
    - /_includes
    - /sass
    - /_sass
    - /_config.yml
    - /_includes
    - /_layouts
    - /_sass
    - /_site
    - /assets
    - /CNAME
    - /config.rb
    - /css
    - /feed.xml
    - /Gemfile
    - /Gemfile.lock
    - /index.md
    - /README.md
    - /sass
