# Site settings
title: DC Capital Striders
email: contact@dccapitalstriders.com
description: > # this means to ignore newlines until "baseurl:"
  DC Capital Striders is a community of runners in Washington, D.C., Northern Virginia, and Maryland. Membership is free and open to anyone. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dccapitalstriders.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title/

# Collections
collections:
  events:
    permalink: /events/:name/
    output: true

# Prose
prose:
  metadata:
    _events:
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
          value: "event"
      - name: "date-year"
        field:
          label: "year"
          element: "text"
      - name: "date-month"
        field:
          label: "month"
          element: "text"
      - name: "date-day"
        field:
          label: "day of month"
          element: "text"
      - name: "teaser"
        field:
          element: "textarea"
          label: "teaser"
      - name: "category"
        field:
          element: "select"
          label: "category"
          options:
           - name: "events"
             value: "events"
           - name: "races"
             value: "races"
      - name: "featured"
        field:
          element: "checkbox"
          label: "featured"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
  ignore:
    - _config.yml
    - /.sass-cache
    - /_layouts
    - /_includes
    - /sass
    - /_sass
    - /_config.yml
    - /_includes
    - /_layouts
    - /_sass
    - /_site
    - /assets
    - /CNAME
    - /config.rb
    - /css
    - /feed.xml
    - /Gemfile
    - /Gemfile.lock
    - /index.md
    - /README.md
    - /sass
